name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write # Required for pushing to gh-pages
      pages: write # Required for GitHub Pages deployment
      id-token: write # Required for actions/deploy-pages
    steps:
      - name: Checkout AUB Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Repository Contents
        run: |
          ls -R || echo "No files in repository"
          echo "Images directory:"
          ls -R images || echo "No images directory"
          echo "Root directory:"
          ls -R . || echo "No files in root"

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: none # No build step needed for static files

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          source-path: . # Deploy everything in the main branch (images/ and Next.js output)