name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write # Required for pushing to gh-pages
      pages: write # Required for GitHub Pages deployment
      id-token: write # Required for actions/deploy-pages
    steps:
      - name: Checkout AUB Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Repository Contents
        run: |
          ls -R || echo "No files in repository"
          echo "Images directory:"
          ls -R images || echo "No images directory"
          echo "Root directory:"
          ls -R . || echo "No files in root"
          git branch -a || echo "No branches found"

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Initialize gh-pages Branch
        run: |
          git checkout --orphan gh-pages || git checkout gh-pages
          git rm -rf . || true
          git clean -fd || true
          touch .nojekyll # Prevent Jekyll processing
          git add .nojekyll
          git commit -m "Initialize gh-pages branch" || echo "No changes to commit"
          git push origin gh-pages --force || echo "gh-pages already up to date"

      - name: Copy Files to gh-pages
        run: |
          git checkout main
          cp -r ./* gh-pages-tmp/
          git checkout gh-pages
          rm -rf ./* || true
          cp -r gh-pages-tmp/* ./
          rm -rf gh-pages-tmp
          git add .
          git commit -m "Deploy images and Next.js output to gh-pages" || echo "No changes to commit"
          git push origin gh-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          source-path: . # Deploy everything in gh-pages branch