name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main # Changed from 'dis' as per previous discussion, assuming your first workflow pushes to 'main'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read # Changed to 'read' because you're no longer pushing to 'gh-pages' within this workflow
      pages: write
      id-token: write

    steps:
      - name: Checkout AUB Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Still good for debugging/visibility, but less critical here

      - name: Debug Main Branch Contents
        run: |
          echo "Main branch contents:"
          ls -R || echo "No files in repository"
          echo "Optimized images directory:"
          ls -R optimized-images || echo "No optimized-images directory"
          echo "Root directory files:"
          find . -maxdepth 1 -type f || echo "No files in root"

      # --- NEW STEP: Upload the pages artifact ---
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3 # Use v3 or later
        with:
          path: './' # This tells the action to upload everything in the current directory (your AUB repo's main branch content)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # No 'with: source-path: .' needed here anymore.
        # It implicitly uses the artifact uploaded by 'actions/upload-pages-artifact'.