name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Checkout AUB Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Main Branch Contents
        run: |
          echo "Main branch contents:"
          ls -R || echo "No files in repository"
          echo "Images directory:"
          ls -R images || echo "No images directory"
          echo "Root directory files:"
          find . -maxdepth 1 -type f || echo "No files in root"

      - name: Setup gh-pages Branch
        run: |
          git checkout --orphan gh-pages || git checkout gh-pages
          git rm -rf . || true
          git clean -fd || true
          cp -r . ../main-files
          git checkout main
          git checkout gh-pages
          rm -rf ./*
          cp -r ../main-files/* ./
          git add .
          git commit -m "Deploy to gh-pages" || echo "No changes to commit"
          git push origin gh-pages --force

      - name: Debug gh-pages Branch
        run: |
          echo "gh-pages branch contents:"
          ls -R || echo "No files in gh-pages"
          find . -maxdepth 1 -type f || echo "No files in root"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          source-path: .