name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write # Required for pushing to gh-pages
      pages: write # Required for GitHub Pages deployment
      id-token: write # Required for actions/deploy-pages
    steps:
      - name: Checkout AUB Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Repository Contents
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing all files in main branch:"
          ls -R || echo "No files in repository"
          echo "Images directory:"
          ls -R images || echo "No images directory"
          echo "Root directory (excluding .git, .github):"
          find . -maxdepth 1 -not -path './.git' -not -path './.github' -not -path '.' || echo "No files in root"
          git branch -a || echo "No branches found"
          git status || echo "Git status unavailable"

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Initialize gh-pages Branch
        run: |
          git checkout --orphan gh-pages || git checkout gh-pages
          # Clear files except .git and .nojekyll
          find . -maxdepth 1 -not -path './.git' -not -path '.' -not -name '.nojekyll' -exec rm -rf {} \;
          touch .nojekyll # Prevent Jekyll processing
          git add .nojekyll
          git commit -m "Initialize gh-pages branch" || echo "No changes to commit"
          git push origin gh-pages --force || echo "gh-pages already up to date"

      - name: Copy Files to gh-pages
        run: |
          # Store repository root
          REPO_ROOT=$(pwd)
          git checkout main
          mkdir -p "$REPO_ROOT/gh-pages-tmp" # Create temporary directory
          # Copy files, excluding .git and .github
          rsync -av --delete --exclude='.git' --exclude='.github' ./* "$REPO_ROOT/gh-pages-tmp/" || echo "No files to copy"
          echo "Listing files in gh-pages-tmp:"
          ls -R "$REPO_ROOT/gh-pages-tmp" || echo "No files in gh-pages-tmp"
          git checkout gh-pages
          # Clear files except .git and .nojekyll
          find . -maxdepth 1 -not -path './.git' -not -path '.' -not -name '.nojekyll' -exec rm -rf {} \;
          if [ -n "$(ls -A "$REPO_ROOT/gh-pages-tmp")" ]; then
            cp -r "$REPO_ROOT/gh-pages-tmp"/* ./
          else
            echo "No files to copy to gh-pages"
            exit 0 # Exit gracefully if no files
          fi
          rm -rf "$REPO_ROOT/gh-pages-tmp"
          git add .
          git commit -m "Deploy images and Next.js output to gh-pages" || echo "No changes to commit"
          git push origin gh-pages

      - name: Debug gh-pages Contents
        run: |
          git checkout gh-pages
          echo "Current directory: $(pwd)"
          echo "Listing files in gh-pages branch:"
          ls -R || echo "No files in gh-pages"
          echo "Images directory in gh-pages:"
          ls -R images || echo "No images directory"
          git status || echo "Git status unavailable"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          source-path: . # Deploy everything in gh-pages branch